name: 'Install dependencies'
description: 'Installs and caches node modules'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        yarn install
        yarn run thx check-git-status

    - name: Check dependencies
      shell: bash
      run: |
        yarn deps -v

    - name: node_modules cache
      uses: actions/cache/save@v4
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
          !node_modules/.cache/nx
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}
