name: 'Build code'
description: 'Runs the build'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '16'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: node_modules cache
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Run build
      shell: bash
      run: |
        yarn build -v
