# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.7
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "yarn.lock" }}

      - run: yarn global add lerna
      - run: yarn lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}

      - run: yarn lint
      - run: yarn ts
      - run: yarn test
      - run: yarn build

  publish:
    docker:
      - image: circleci/node:12.7
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run: npm install lerna
      - run: yarn lerna bootstrap
      - run: yarn build

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
