# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - run:
          name: Generate pkghash
          command: yarn pkghash
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum ".packages-hash" }}
          - v1-dependencies-

      - run: yarn global add lerna
      - run: yarn lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum ".packages-hash" }}

      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: yarn ts

  publish:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum ".packages-hash" }}
            - v1-dependencies-
      - run: npm install lerna
      - run: yarn lerna bootstrap
      - run: yarn build

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
