name: 'Check typescript'
description: 'Checks typescript'
inputs:
  node-version:
    description: 'Node version to use'
    required: true
    default: '20'
runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: node_modules cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-nm-${{ hashFiles('yarn.lock') }}

    - name: Run ts
      shell: bash
      run: |
        yarn ts -v
